config/routes.rb
Rails.application.routes.draw do
  resources :users
  # resources :articles
  # here it means we are calling file application_controller.rb but all we need is to write word application and the rest will be considered 
  # in order to specify the method you planning to use, type it after filename using #
  # root 'application#hello'

  root 'pages#home'

  # this translated to GET request to 'about; page
  get 'about', to: 'pages#about'

  # only: [:show] we describe only routes we need, because by default it will create things like post, delete and etc
  # to see all possible routes we have in the app "rails routes --expanded"
  # show, index, new, create are reserved words
  resources :articles_v2s
  
  # to expose all the possible routes for uses we need to call resources
  get 'signup', to: 'users#new'
  #excepting method new because we already described it above
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
  <%= msg%>
<%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
       <li class="nav-item">
        <%= link_to "Categories", categories_path, class: "nav-link" %>
      </li>
      <% if logged_in? && current_user.admin?%>
      <li class="nav-item">
        <%= link_to "Create Categories", new_category_path, class: "nav-link" %>
      </li>
      <%end%>
      <li class="nav-item dropdown">
          <%= link_to 'Articles listing', articles_v2s_path(@article)%> 
      </li>
     
      <% if logged_in? %>
        <li class="nav-item">
        <%# current_user is our helper method which returns current user object thats why we can take it here %>
          Welcome 
          <%= "(Admin)" if current_user.admin? %>
          <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
        <li class="nav-item">
          <%= link_to 'View your profile', user_path(current_user), class: "nav-link" %>
        </li>
         <%= link_to "Edit your profile", edit_user_path(current_user), class: "nav-link" %>
         <%= link_to "Delete profile", user_path(current_user), class: "nav-link", method: :delete, data: { confirm: "Are you sure?" } %> 

      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>